{'author': 'Add your name here',
 'description': 'lm-sensors plugin for check_mk 2',
 'download_url': 'http://example.com/lmsensors2/',
 'files': {'agent_based': ['lmsensors2.py'],
           'agents': ['plugins/lmsensors2'],
           'alert_handlers': [],
           'bin': [],
           'checkman': [],
           'checks': [],
           'doc': [],
           'inventory': [],
           'lib': [],
           'locales': [],
           'mibs': [],
           'notifications': [],
           'pnp-templates': [],
           'web': []},
 'name': 'lmsensors2',
 'title': 'lm-sensors plugin for check_mk 2',
 'version': '1.0',
 'version.min_required': '2.0.0p1',
 'version.packaged': '2.0.0p5',
 'version.usable_until': None}
